language: node_js
dist: trusty
sudo: required
node_js:
  - "7"
  - "6"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
  - npm rebuild phantom-prebuilt
script:
  - npm run test
